Repository isabellaberekdar/capstone-front-end, pull requests merged in 2020-01, with the labels that each got.

#35 Homestyle2
  public/images/placeholder.png
  src/components/containers/NavbarContainer.jsx
  src/components/views/OfficialCard.css
  src/components/views/OfficialCard.jsx
Labels: enhancement, needs-improvement

#38 Homestyle2
  src/components/containers/HomeContainer.jsx
  src/components/containers/NavbarContainer.jsx
  src/components/containers/OfficialContainer.jsx
  src/components/views/HomeView.jsx
  src/components/views/OfficialView.jsx
  src/store/utilities/official.js
Labels: enhancement, needs-improvement

#49 Homestyle2
  public/images/homeheader2.png
  public/images/pres.png
  public/images/speaker.png
  public/images/vp.png
  src/App.js
  src/components/containers/Footer.jsx
  src/components/containers/HomeContainer.jsx
  src/components/containers/NavbarContainer.jsx
  src/components/routes/RoutesView.jsx
  src/components/views/Footer.css
  src/components/views/Home.css
  src/components/views/HomeView.jsx
  src/components/views/Navbar.css
  src/components/views/OfficialCard.css
  src/components/views/OfficialCard.jsx
  src/components/views/fonts/besleymed.otf
Labels: needs-improvement

#52 Login style branch
  src/components/containers/AuthFormContainer.jsx
  src/components/containers/NavbarContainer.jsx
  src/components/containers/index.js
  src/components/routes/RoutesView.jsx
  src/components/views/Footer.css
  src/components/views/Navbar.css
Labels: enhancement, needs-improvement

#55 Login signup style
  .gitignore
  src/components/containers/AuthFormContainer.jsx
  src/components/containers/NavbarContainer.jsx
  src/components/containers/OfficialContainer.jsx
  src/components/views/AuthForm.css
  src/components/views/AuthFormView.jsx
  src/components/views/Home.css
  src/components/views/HomeView.jsx
  src/components/views/Navbar.css
  src/components/views/NewsArticles.css
  src/components/views/NewsArticlesContainer.jsx
  src/components/views/NewsArticlesView.jsx
  src/components/views/OfficialCard.css
  src/components/views/OfficialView.css
  src/components/views/OfficialView.jsx
  src/store/utilities/official.js
Labels: enhancement, help wanted, needs-improvement

#70 Official styling
  package-lock.json
  package.json
  public/images/credit.txt
  public/images/facebook-card.svg
  public/images/homeheader.png
  public/images/homeheader3.png
  public/images/homepage-icon.svg
  public/images/twitter-card.svg
  public/images/youtube-card.svg
  src/App.css
  src/App.js
  src/components/containers/NavbarContainer.jsx
  src/components/routes/Routes.css
  src/components/routes/RoutesView.jsx
  src/components/views/Funding.css
  src/components/views/FundingView.jsx
  src/components/views/Home.css
  src/components/views/HomeView.jsx
  src/components/views/Navbar.css
  src/components/views/NewsArticles.css
  src/components/views/NewsArticlesView.jsx
  src/components/views/OfficialCard.css
  src/components/views/OfficialCard.jsx
  src/components/views/OfficialView.css
  src/components/views/OfficialView.jsx
Labels: enhancement, needs-improvement

#90 Official styling
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/components/containers/FundingContainer.jsx
  src/components/containers/SingleSideNav.jsx
  src/components/routes/RoutesView.jsx
  src/components/views/AuthForm.css
  src/components/views/Footer.css
  src/components/views/Funding.css
  src/components/views/FundingCard.css
  src/components/views/FundingCard.jsx
  src/components/views/Home.css
  src/components/views/MessageBoardCollection.jsx
  src/components/views/Messageboard.css
  src/components/views/NewsArticles.css
  src/components/views/NewsArticlesView.jsx
  src/components/views/OfficialView.css
  src/components/views/OfficialView.jsx
  src/components/views/SingleSideNav.css
Labels: enhancement, help wanted, needs-improvement
